const Enum = require('../enum');
module.exports = new Enum({
  '0': 'lock_event',
  '1': 'GetNotifications',
  '2': 'status',
  '3': 'SetParameter',
  '4': 'GetParameter',
  '5': 'ClearParameter',
  '6': 'ClearLog',
  '7': 'MoveMotorDegrees',
  '8': 'ReleaseLockEvent',
  '9': 'ReleaseNotification',
  '10': 'Unlock',
  '11': 'Lock',
  '12': 'CalibrateLock',
  '13': 'PlayAudio', // ids:32, 33, 34, 35
  '14': 'Led', // Nothing seems valid, everything results in all red flash
  '15': 'ClearNotifications',
  '16': 'SetRtc',
  '17': 'SecureUnlock', // Lock does not know about this
  '18': 'ForcePairing',
  '19': 'SetKIv',
  '20': 'OtaQueryStatus',
  '21': 'OtaWriteSlice',
  '22': 'OtaCreateAsset',
  '23': 'InfoForAsset',
  '24': 'OtaDeleteAsset',
  '25': 'OtaQuerySlice',
  '26': 'OtaError',
  '27': 'OtaProgram',
  '28': 'OtaResetAssetStore',
  '29': 'SetAndModifyCurrentSlice',
  '30': 'OtaReserved',
  '32': 'MotorPolarityDiscovery',
  '33': 'NopAck',
  '34': 'Nop',
  '35': '8051Serial',
  '36': 'FactoryReset',
  '37': 'MotorTest',
  '38': 'FirmwareVersion',
  '39': 'KeycodeSet',
  '40': 'KeycodeClear',
  '41': 'KeycodeClearAll',
  '42': 'KeycodeUnlock',
  '43': 'KeycodeAccess',
  '44': 'KeycodeCommit',
  '45': 'GetLog',
  '46': 'HomekitReset',
  //47 exists but don't know what it is
  '48': 'TimezoneInfo'
});
