const Enum = require('../enum');
// Parameters 0-78 default to 0 on a factory reset
module.exports = new Enum({
  '0': 'BackoffTimeMs',
  '1': 'AnimationPeriodMs', // the delay in ms between led frame. (have tested 5-500)
  '2': 'BatteryType',
  '3': 'SerialNumberPt2',
  '4': 'SerialNumberPt1',
  '5': 'ManufactureInfo', // Default 0:
  '6': 'ManufactureDate', // Default 0:
  '7': 'AudioVolume', // 0-7, where 0 is the loudest setting. Default = 0
  '8': 'LedBrightness', // Does not appear to do anything Default = 255
  '9': 'CurrentKdt',
  '10': 'CurrentKi',
  '11': 'CurrentKp',
  '12': 'CurrentILimit',
  '13': 'PosKdt',
  '14': 'PosKi',
  '15': 'PosKp',
  '16': 'PosILimit',
  '17': 'RssiThreshold',
  '18': 'RssiFilter',
  '19': 'AccThreshold',
  '20': 'KockThreshold',
  '21': 'KockFilter',
  '22': 'StallCurrentLimit',
  '23': 'PwmLimit',
  '24': 'StallPositionCw',
  '25': 'StallPositionCcw',
  '26': 'TargetPositionCw',
  '27': 'TargetPositionCcw',
  '28': 'BatterySocThreshold',
  '29': 'MinStallTimeMs',
  '30': 'BackoffAngle',
  '31': 'AngleThreshold',
  '32': 'Orientation',
  '33': 'TemperatureWarning',
  '34': 'TemperatureAlarm',
  '35': 'CurrentLimit',
  '36': 'MinBatteryVoltageMv',
  '37': 'LockOperationTimeout',
  '38': 'BackoffCurrentMa',
  '39': 'CurrentMeasureIntervalMs',
  '40': 'RelockTimeInSeconds', //This one does not follow the same format. It is 2 16bit uints.
  '41': 'UnlockedTol', // Default: 0
  '42': 'LockedTol', // Default: -1
  '43': 'MaxStallCurrentError',
  '44': 'AutocalibrationMs',
  '45': 'MotorPolarity',
  '46': 'AutocalibrationAttempts',
  '47': 'PwmDzone',
  '48': 'NumberRetries',
  '49': 'RetryTimer',
  '50': 'HighAngleLimit',
  '51': 'Simulated', // Default: -1, does not seem to do anything
  '52': 'AngleTau',
  '53': 'AccVerbose',
  '54': 'MotionVerbose', // Default: 0, does not seem to do anything 
  '55': 'MinAwakeTime',
  '56': 'AudioEnabled',
  '57': 'BurninTrigger', // Default: 1, set to 0 and reboot to trigger burnin
  '58': 'BurninCycles',
  '59': 'BurninDelay',
  '60': 'BurninCyclesDone',
  '61': 'BurninCyclesSuccess',
  '62': 'BurninFailTol',
  '63': 'BurninCalibrateSuccess',
  '64': 'BurninAttempts',
  '65': 'BurninFailedAttempts',
  '66': 'BurninTimestamp',
  '67': 'BurninNoSleep',
  '68': 'BurninAutorestart',
  '69': 'BurinInitDelay',
  '70': 'BurninProgress',
  '71': 'BurninErrors',
  '72': 'BatteryCriticalThreshold',
  '73': 'BatteryLowThreshold',
  '74': 'BatteryMediumThreshold',
  '75': 'BackoffMinMs',
  '76': 'BackoffSampleCount',
  '77': 'AudioInterDelay',
  '78': 'PoskpBackoff',
  '80': 'BleResetPeriod',
  '81': 'BleResetPeriodConnected',
  '82': 'BleResetPeriodDisconnected',
  '92': 'MotorFaultCurrentLimit',
  '93': 'MotorFaultCurrentWindow',
  '94': 'MotorRetryDelay',
  '95': 'MotorRetryCount',
  '96': 'Motor',
  '97': 'MotorCreepAngle',
  '98': 'MotorCreepPower',
  '99': 'MotorSlewRate',
  '100': 'MotorCreepTimeout',
  '101': 'MotorSeekPower',
  '102': 'MotorSeekSlewRate',
  '103': 'MotorFinishAngle',
  '104': 'MotorFinishPower',
  '105': 'MotorFinishSlewRate',
  '106': 'MotorFinishBackoffDelay',
  '107': 'MotorBackoffPower',
  '108': 'MotorBackoffSlewRate',
  '109': 'MotorBackoffAngle',
  '110': 'MotorBackoffTimeout',
  '111': 'MotorAutoCalibrateWithdrawAngle',
  '112': 'MotorAutoCalibratePower',
  '113': 'MotorAutoCalibrateSlewRate',
  '114': 'MotorAutoCalibrateTimeout',
  '115': 'MotorAutoCalibrateTripCurrent',
  '116': 'MotorAutoCalibrateDelay',
  '117': 'MotorTestCCW',
  '118': 'MotorTestCW',
  '119': 'MotorTestWait',
  '120': 'OtaTiUpdateCounter', // Write 1 to this property to force the ti chip to be programed.
  '121': 'MotorTestFinishTimeout',
  '122': 'MotorTestFinishPower',
  '123': 'MotorTestFaultCurrent',
  '124': 'MotorUpdatePeriod',
  '125': 'EnableKeypadUnlock',
  '126': 'EnableKeypadBacklight',
  '127': 'EnableKeypadOneTouchLock',
  '128': 'KeypadNumFailed',
  '129': 'KeypadTimeFailed',
  '130': 'KeypadTimeout',
  '131': 'KeypadBattery',
  '132': 'BleInactiveTimeout',
  '133': 'HomekitAdvtEnabled',
  '134': 'KeypadPinHigh',
  '135': 'KeypadPinLow',
  //140 is defined but not named
  '141': 'BcmRebootPeriod',
  '142': 'HomekitBleTimeout',
  '143': 'HomekitPairingState'
});
