const Enum = require('../enum');
module.exports = new Enum({
  '0': 'GitHash',
  '1': 'HardwareVersion',
  '2': 'LockState',
  '3': 'AngleOfLock',
  '4': 'TargetAngle',
  '5': 'BatteryLevel',
  '6': 'LedState',
  '7': 'AudioState',
  '8': 'Events',
  '9': 'UnreadEventCount',
  '10': 'Rtc',
  '11': 'TBD',
  '12': 'Success',
  '13': 'TBD1',
  '14': 'HardwareTemperature',
  '15': 'BatteryVoltage',
  '16': 'CurrentHistory0', //Current as in amps
  '17': 'CurrentHistory1',
  '18': 'CurrentHistory2',
  '19': 'CurrentHistory3',
  '20': 'CurrentHistory4',
  '21': 'CurrentHistory5',
  '22': 'CurrentHistory6',
  '23': 'CurrentHistory7',
  '24': 'CurrentHistory8',
  '25': 'CurrentHistory9',
  '26': 'RssiHistory0',
  '27': 'RssiHistory1',
  '28': 'RssiHistory2',
  '29': 'RssiHistory3',
  '30': 'RssiHistory4',
  '31': 'MemX',
  '32': 'MemY',
  '33': 'MemZ',
  '34': 'Motor',
  '35': 'CoulombCountLow',
  '36': 'CoulombCountHigh',
  '37': 'BatteryRunning',
  '38': 'OtaAck',
  '39': 'Accelerometer',
  '40': 'BatteryLevelV2',
  '41': 'GitHashV2', // yeah there is 2 of these
  '42': 'BuildDate',
  '43': 'SelfChecksum',
  '44': 'ArmVersion'

});
